# Get editor completions based on the config schema
"$schema" = 'https://starship.rs/config-schema.json'

# Inserts a blank line between shell prompts
add_newline = true

command_timeout = 2000

[bun]
symbol = 'ğŸ '

[character]
success_symbol = '[âœ](bold green)'
error_symbol = '[âœ](bold red)'

[git_branch]
symbol = 'ğŸŒ³ '

