# Get editor completions based on the config schema
"$schema" = 'https://starship.rs/config-schema.json'

# Inserts a blank line between shell prompts
add_newline = true

[character]
success_symbol = '[ï¡](bold green)'
error_symbol = '[ï¡](bold red)'
vimcmd_replace_one_symbol = '[ï ](bold purple)'
vimcmd_replace_symbol = '[ï ](bold purple)'
vimcmd_visual_symbol = '[ï ](bold yellow)'

[bun]
symbol = 'ğŸ '

# Disable the package module, hiding it from the prompt completely
[package]
disabled = true
