# Get editor completions based on the config schema
"$schema" = 'https://starship.rs/config-schema.json'

# Inserts a blank line between shell prompts
add_newline = true

command_timeout = 2000

[character]
success_symbol = '[âœ](bold green)'
error_symbol = '[âœ](bold red)'

[bun]
symbol = 'ğŸ '

# Disable the package module, hiding it from the prompt completely
[package]
disabled = true
